#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/rapid_transit
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        TYPE: TRACE
